// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/9/2025, 2:42:02 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/plugins/**/*.{js,ts,mjs}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/composables/**/*.{js,ts,mjs}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/utils/**/*.{js,ts,mjs}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["11"] = "C:/Users/sofia/Downloads/Proyecto1_Sofia_Rafael_Arquitectura/Proyecto1_Sofia_Rafael_Arquitectura/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;